	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_8725A2C::
	.incbin "sound/direct_sound_samples/8725A2C.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_872762C::
	.incbin "sound/direct_sound_samples/872762C.bin"

	.align 2
DirectSoundWaveData_872921C::
	.incbin "sound/direct_sound_samples/872921C.bin"

	.align 2
DirectSoundWaveData_872A5D0::
	.incbin "sound/direct_sound_samples/872A5D0.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_872EEA8::
	.incbin "sound/direct_sound_samples/872EEA8.bin"

	.align 2
DirectSoundWaveData_87301B0::
	.incbin "sound/direct_sound_samples/87301B0.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_8734298::
	.incbin "sound/direct_sound_samples/8734298.bin"

	.align 2
DirectSoundWaveData_87364A8::
	.incbin "sound/direct_sound_samples/87364A8.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_87385E4::
	.incbin "sound/direct_sound_samples/87385E4.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_873ECD8::
	.incbin "sound/direct_sound_samples/873ECD8.bin"

	.align 2
DirectSoundWaveData_8740818::
	.incbin "sound/direct_sound_samples/8740818.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_87424B0::
	.incbin "sound/direct_sound_samples/87424B0.bin"

	.align 2
DirectSoundWaveData_87430C0::
	.incbin "sound/direct_sound_samples/87430C0.bin"

	.align 2
DirectSoundWaveData_8743C50::
	.incbin "sound/direct_sound_samples/8743C50.bin"

	.align 2
DirectSoundWaveData_87446EC::
	.incbin "sound/direct_sound_samples/87446EC.bin"

	.align 2
DirectSoundWaveData_8745034::
	.incbin "sound/direct_sound_samples/8745034.bin"

	.align 2
DirectSoundWaveData_8745A7C::
	.incbin "sound/direct_sound_samples/8745A7C.bin"

	.align 2
Cry_Sanae::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Alice::
	.incbin "sound/direct_sound_samples/cries/alice.bin"

	.align 2
Cry_Reisen::
	.incbin "sound/direct_sound_samples/cries/reisen.bin"

	.align 2
Cry_LilyWhite::
	.incbin "sound/direct_sound_samples/cries/lily_white.bin"

	.align 2
Cry_LilyBlack::
	.incbin "sound/direct_sound_samples/cries/lily_black.bin"

	.align 2
Cry_Momiji::
	.incbin "sound/direct_sound_samples/cries/momiji.bin"

	.align 2
Cry_Shizuha::
	.incbin "sound/direct_sound_samples/cries/shizuha.bin"

	.align 2
Cry_Medicine::
	.incbin "sound/direct_sound_samples/cries/medicine.bin"

	.align 2
Cry_Koakuma::
	.incbin "sound/direct_sound_samples/cries/koakuma.bin"

	.align 2
Cry_Nazrin::
	.incbin "sound/direct_sound_samples/cries/nazrin.bin"

	.align 2
Cry_Tokiko::
	.incbin "sound/direct_sound_samples/cries/tokiko.bin"

	.align 2
Cry_Remilia::
	.incbin "sound/direct_sound_samples/cries/remilia.bin"

	.align 2
Cry_Cirno::
	.incbin "sound/direct_sound_samples/cries/cirno.bin"

	.align 2
Cry_Rumia::
	.incbin "sound/direct_sound_samples/cries/rumia.bin"

	.align 2
Cry_AliceDolls::
	.incbin "sound/direct_sound_samples/cries/alice_dolls.bin"

	.align 2
Cry_Flandre::
	.incbin "sound/direct_sound_samples/cries/flandre.bin"

	.align 2
Cry_Youmu::
	.incbin "sound/direct_sound_samples/cries/youmu.bin"

	.align 2
Cry_Yukari::
	.incbin "sound/direct_sound_samples/cries/yukari.bin"

	.align 2
Cry_Suika::
	.incbin "sound/direct_sound_samples/cries/suika.bin"

	.align 2
Cry_Mystia::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Minoriko::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Keine::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_KeineB::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Iku::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Koishi::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Yamame::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Chen::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Yorihime::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kaguya::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Mokou::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Hatate::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Letty::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Patchouli::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Yuugi::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Tenshi::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Parsee::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Murasa::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kisume::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kogasa::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Satori::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Eirin::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Ran::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Daiyousei::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Nitori::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Hina::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Komachi::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Yuyuko::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Meiling::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Sakuya::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Lunasa::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Merlin::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Lyrica::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Layla::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kanako::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Rin::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Utsuho::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Ichirin::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Sunny::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Luna::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Star::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Yuuka::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Aya::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Eiki::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Shou::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Wriggle::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Tewi::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kedama::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Nue::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Suwako::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_ReisenTwo::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Marisa::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Reimu::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Byakuren::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Konngara::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kikuri::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Yuugenma::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Toyohime::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Sariel::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_AVIVIT::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Akyuu::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Genji::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Tori::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Namazu::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Elly::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Orange::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Youki::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Chiyuri::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Yumemi::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Ellen::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kazami::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Meira::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Sara::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Louise::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Margatroid::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kana::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Hakurei::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kirisame::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kotohime::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Yumeko::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Shinki::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_MimiChan::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Ruukoto::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Rika::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Mugetsu::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Gengetsu::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kurumi::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Rikako::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Rinnosuke::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Yuki::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Mai::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Shingyoku::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Tenma::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_DarkAlice::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Elis::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Mima::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Sendai::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_ZombieF::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_AkiSisters::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Tensoku::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kyouko::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Yoshika::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Seiga::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Tojiko::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Futo::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Miko::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Mamizou::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kasen::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kokoro::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Sekibanki::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kagerou::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Wakasagi::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Benben::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Yatsuhashi::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Raiko::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Seija::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Sukuna::
	.incbin "sound/direct_sound_samples/cries/sukuna.bin"

	.align 2
Cry_Kosuzu::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Sumireko::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_AdCirno::
	.incbin "sound/direct_sound_samples/cries/advent_cirno.bin"

	.align 2
Cry_AdReisen::
	.incbin "sound/direct_sound_samples/cries/advent_reisen.bin"

	.align 2
Cry_AdMeiling::
	.incbin "sound/direct_sound_samples/cries/advent_meiling.bin"

	.align 2
Cry_AdMystia::
	.incbin "sound/direct_sound_samples/cries/advent_mystia.bin"

	.align 2
Cry_AdLetty::
	.incbin "sound/direct_sound_samples/cries/advent_letty.bin"

	.align 2
Cry_AdTewi::
	.incbin "sound/direct_sound_samples/cries/advent_tewi.bin"

	.align 2
Cry_AdMarisa::
	.incbin "sound/direct_sound_samples/cries/advent_marisa.bin"

	.align 2
Cry_AdAlice::
	.incbin "sound/direct_sound_samples/cries/advent_alice.bin"

	.align 2
Cry_AdMokou::
	.incbin "sound/direct_sound_samples/cries/advent_mokou.bin"

	.align 2
Cry_AdYukari::
	.incbin "sound/direct_sound_samples/cries/advent_yukari.bin"

	.align 2
Cry_AdRan::
	.incbin "sound/direct_sound_samples/cries/advent_ran.bin"

	.align 2
Cry_AdChen::
	.incbin "sound/direct_sound_samples/cries/advent_chen.bin"

	.align 2
Cry_Ayakashi::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Vivit::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Unown::
	.incbin "sound/direct_sound_samples/cries/unown.bin"

	.align 2
Cry_Leafeon::
	.incbin "sound/direct_sound_samples/cries/leafeon.bin"

	.align 2
Cry_Glaceon::
	.incbin "sound/direct_sound_samples/cries/glaceon.bin"

	.align 2
Cry_Dummy::
	.incbin "sound/direct_sound_samples/cries/dummy.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_88D6978::
	.incbin "sound/direct_sound_samples/88D6978.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_88DBBC0::
	.incbin "sound/direct_sound_samples/88DBBC0.bin"

	.align 2
DirectSoundWaveData_88DC220::
	.incbin "sound/direct_sound_samples/88DC220.bin"

	.align 2
DirectSoundWaveData_88DC704::
	.incbin "sound/direct_sound_samples/88DC704.bin"

	.align 2
DirectSoundWaveData_88DD054::
	.incbin "sound/direct_sound_samples/88DD054.bin"

	.align 2
DirectSoundWaveData_88DDAC4::
	.incbin "sound/direct_sound_samples/88DDAC4.bin"

	.align 2
DirectSoundWaveData_88DDDE4::
	.incbin "sound/direct_sound_samples/88DDDE4.bin"

	.align 2
DirectSoundWaveData_88DEA6C::
	.incbin "sound/direct_sound_samples/88DEA6C.bin"

	.align 2
DirectSoundWaveData_88DF08C::
	.incbin "sound/direct_sound_samples/88DF08C.bin"

	.align 2
DirectSoundWaveData_88DF414::
	.incbin "sound/direct_sound_samples/88DF414.bin"

	.align 2
DirectSoundWaveData_88E01F8::
	.incbin "sound/direct_sound_samples/88E01F8.bin"

	.align 2
DirectSoundWaveData_88E0B68::
	.incbin "sound/direct_sound_samples/88E0B68.bin"

	.align 2
DirectSoundWaveData_88E0F04::
	.incbin "sound/direct_sound_samples/88E0F04.bin"

	.align 2
DirectSoundWaveData_88E16B8::
	.incbin "sound/direct_sound_samples/88E16B8.bin"

	.align 2
DirectSoundWaveData_88E2414::
	.incbin "sound/direct_sound_samples/88E2414.bin"

	.align 2
DirectSoundWaveData_88E2658::
	.incbin "sound/direct_sound_samples/88E2658.bin"

	.align 2
DirectSoundWaveData_88E3498::
	.incbin "sound/direct_sound_samples/88E3498.bin"

	.align 2
DirectSoundWaveData_88E3DEC::
	.incbin "sound/direct_sound_samples/88E3DEC.bin"

	.align 2
DirectSoundWaveData_88E4140::
	.incbin "sound/direct_sound_samples/88E4140.bin"

	.align 2
DirectSoundWaveData_88E4774::
	.incbin "sound/direct_sound_samples/88E4774.bin"

	.align 2
DirectSoundWaveData_88E53E0::
	.incbin "sound/direct_sound_samples/88E53E0.bin"

	.align 2
DirectSoundWaveData_88E5978::
	.incbin "sound/direct_sound_samples/88E5978.bin"

	.align 2
DirectSoundWaveData_88E647C::
	.incbin "sound/direct_sound_samples/88E647C.bin"

	.align 2
DirectSoundWaveData_88E6A80::
	.incbin "sound/direct_sound_samples/88E6A80.bin"

	.align 2
DirectSoundWaveData_88E6C78::
	.incbin "sound/direct_sound_samples/88E6C78.bin"

	.align 2
DirectSoundWaveData_88E75DC::
	.incbin "sound/direct_sound_samples/88E75DC.bin"

	.align 2
DirectSoundWaveData_88E8568::
	.incbin "sound/direct_sound_samples/88E8568.bin"

	.align 2
DirectSoundWaveData_88E8BA0::
	.incbin "sound/direct_sound_samples/88E8BA0.bin"

	.align 2
DirectSoundWaveData_88E9674::
	.incbin "sound/direct_sound_samples/88E9674.bin"

	.align 2
DirectSoundWaveData_88EA5B8::
	.incbin "sound/direct_sound_samples/88EA5B8.bin"

	.align 2
DirectSoundWaveData_88EAB30::
	.incbin "sound/direct_sound_samples/88EAB30.bin"

	.align 2
DirectSoundWaveData_88EB97C::
	.incbin "sound/direct_sound_samples/88EB97C.bin"

	.align 2
DirectSoundWaveData_88EC884::
	.incbin "sound/direct_sound_samples/88EC884.bin"

	.align 2
DirectSoundWaveData_88ED358::
	.incbin "sound/direct_sound_samples/88ED358.bin"

	.align 2
DirectSoundWaveData_88EDEEC::
	.incbin "sound/direct_sound_samples/88EDEEC.bin"

	.align 2
DirectSoundWaveData_88EE8C4::
	.incbin "sound/direct_sound_samples/88EE8C4.bin"

	.align 2
DirectSoundWaveData_88EEF04::
	.incbin "sound/direct_sound_samples/88EEF04.bin"

	.align 2
DirectSoundWaveData_88EF9E4::
	.incbin "sound/direct_sound_samples/88EF9E4.bin"

	.align 2
DirectSoundWaveData_88F0020::
	.incbin "sound/direct_sound_samples/88F0020.bin"

	.align 2
DirectSoundWaveData_88F0738::
	.incbin "sound/direct_sound_samples/88F0738.bin"

	.align 2
DirectSoundWaveData_88F1074::
	.incbin "sound/direct_sound_samples/88F1074.bin"

	.align 2
DirectSoundWaveData_88F1830::
	.incbin "sound/direct_sound_samples/88F1830.bin"

	.align 2
DirectSoundWaveData_88F1D94::
	.incbin "sound/direct_sound_samples/88F1D94.bin"

	.align 2
DirectSoundWaveData_88F2B08::
	.incbin "sound/direct_sound_samples/88F2B08.bin"

	.align 2
DirectSoundWaveData_88F2F84::
	.incbin "sound/direct_sound_samples/88F2F84.bin"

	.align 2
DirectSoundWaveData_88F3470::
	.incbin "sound/direct_sound_samples/88F3470.bin"

	.align 2
DirectSoundWaveData_88F3C38::
	.incbin "sound/direct_sound_samples/88F3C38.bin"

	.align 2
DirectSoundWaveData_88F4834::
	.incbin "sound/direct_sound_samples/88F4834.bin"

	.align 2
DirectSoundWaveData_88F4BAC::
	.incbin "sound/direct_sound_samples/88F4BAC.bin"

	.align 2
DirectSoundWaveData_88F5368::
	.incbin "sound/direct_sound_samples/88F5368.bin"

	.align 2
DirectSoundWaveData_88F5FCC::
	.incbin "sound/direct_sound_samples/88F5FCC.bin"

	.align 2
DirectSoundWaveData_88F6498::
	.incbin "sound/direct_sound_samples/88F6498.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
